<?php

/**
 * Implements hook_cron().
 * Aggregate, format and send Digest emails.
 */
function message_digest_cron() {
  $interval = "1 day"; // @TODO: DO NOT HARDCODE THIS.
  $last_run = variable_get('message_digest_last_run', 0);
  if ($last_run > strtotime("-" . $interval)) {
    return;
  }

  foreach (message_notify_get_notifiers() as $plugin_name => $plugin) {
    if (strpos($plugin_name, 'digest') === FALSE) {
      // Only load the "Digest" notifiers and skip the rest.
      continue;
    }
    $plugin = message_notify_get_notifier($plugin_name);
    $class = ctools_plugin_load_class('message_notify', 'notifier', $plugin_name, 'class');
    $notifier = new $class($plugin, new Message());

    // Gather up all the messages into neat little digests and send 'em out.
    $digests = $notifier->aggregate();
    foreach ($digests as $uid => $messages) {
      $formatted_messages = $notifier->format($messages);
      $result = $notifier->deliverDigest($uid, $formatted_message);
    }
  }

  //variable_set('message_digest_last_run', time()); @TODO UNCOMMENT THIS
}

/**
 * Implements hook_ctools_plugin_api().
 */
function message_digest_ctools_plugin_api($module, $api) {
  if ($module == 'message_notify' && $api == 'notifier') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function message_digest_ctools_plugin_directory($module, $plugin) {
  if ($module == 'message_notify') {
    return 'plugins/' . $plugin;
  }
}
